# @package _group_

stream_sizes: [1]
has_dynamic_features: [false]
stream_weights: [1]
stream_wise_training: false

netG:
  _target_: nnsvs.model.FeedForwardNet
  in_dim: 420
  out_dim: 1
  hidden_dim: 128
  num_layers: 2
  dropout: 0.5
