# (mgc, lf0, vuv, bap, vib, vib_flags)
stream_sizes: [180, 3, 1, 15, 6, 1]
has_dynamic_features: [true, true, false, true, true, false]
num_windows: 3
# If None, automatically set based on stream sizes
stream_weights:

netG:
  _target_: nnsvs.model.ResF0Conv1dResnet
  in_dim: 348
  out_dim: 206
  hidden_dim: 128
  num_layers: 6
  # NOTE: you MUST set in_lf0_idx and out_lf0_idx correctly
  # otherwise the model does't work at all
  in_lf0_idx: 300
  out_lf0_idx: 180
  # Please leave the following parameters unspecified if you want to
  # find the corresponding values automatically from in/out scalers.
  in_lf0_min: null
  in_lf0_max: null
  out_lf0_mean: null
  out_lf0_scale: null

